# Generated by Django 5.1.2 on 2024-11-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0002_goods_delete_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='buyer',
            field=models.ManyToManyField(related_name='goods', to='task1.buyer'),
        ),
    ]
